overrides:
  "@mdbase-dev/connect": "file:vendor/mdbase-dev-connect-0.1.0-beta.63-b1ba9e676c40.tgz"
  "@mdbase-dev/connect-protocol": "file:vendor/mdbase-dev-connect-protocol-0.1.0-beta.63-b1ba9e676c40.tgz"
  "@mdbase-dev/pickle": "file:vendor/mdbase-dev-pickle-0.1.0-beta.63-b1ba9e676c40.tgz"

allowBuilds:
  sharp: true
