overrides:
  "@mdbase-dev/connect": "file:vendor/mdbase-dev-connect-0.1.0-beta.58-557a548bb90d.tgz"
  "@mdbase-dev/connect-protocol": "file:vendor/mdbase-dev-connect-protocol-0.1.0-beta.58-557a548bb90d.tgz"
  "@mdbase-dev/pickle": "file:vendor/mdbase-dev-pickle-0.1.0-beta.58-557a548bb90d.tgz"

allowBuilds:
  sharp: true
